### ISSUE TITLE
One and the same query works when string and does not, when function

### ISSUE THREAD

**Issue by delianjekov** [FlavioLionelRita/lambdaorm#179]
The following does not work:

```
const query = (ordNo: number) =>
    Orders
    .filter(o => o.orderNo > ordNo)
    .map(o => {result:avg(o.total)})

const result = orm.execute(query, { ordNo: 5 });
```

While this one works:

```
const query = `Orders
        .filter(o => o.orderNo > ordNo)
        .map(o => {result:avg(o.total)})`

const result = orm.execute(query, { ordNo: 5 });
```

The error is:
Uncaught Error Error: attribute  without value

There must be something wrong with the parsing.

**Comment by FlavioLionelRita** [comment]
Hello good morning...
Sorry for the delay in responding and thank you very much for your interest in the bookstore.

The expression you report to me is not written correctly.
The Orders entity does not have an orderNo property but rather an Id (At least in the northwind examples that I was using as an example)

I've added a lab so you can try it out in [https://github.com/FlavioLionelRita/lambdaorm-labs/tree/main/labs/issue-179](https://github.com/FlavioLionelRita/lambdaorm-labs/tree/main/labs/issue-179)

```ts
import { orm } from 'lambdaorm'
import { Orders } from './northwind/domain'
( async ()=> {
	try {		
		await orm.init('lambdaORM.yaml')
		const query = (ordNo: number) => Orders.details.filter(o => o.orderId === ordNo).map(o => ({ ordNo:o.orderId, total: avg(o.unitPrice * o.quantity )}))
		const result = await orm.execute(query, { ordNo: 5 }, {stage:'MySQL'});
        console.log(JSON.stringify(result))		
	} catch (error:any) {
		console.error(error.stack)
	} finally {
		await orm.end()
	}
})()
```
